name = "workhours-api"
main = "src/index.ts"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "workhours"
database_id = "90d5cdca-164b-421e-8783-63b778e8c99a"
